### ISSUE TITLE
`vagrant up` from a fresh checkout fails

### ISSUE THREAD

**Issue by timheap** [springload/wagtailsites#8]
It appears no Django database configuration is set automatically by the provisioning script, so attempting to run `manage.py migrate` fails with:

```
django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "postgres"
```

The provisioning script should automatically set up a local database user and a `settings/local.py`, or the README should contain instructions on how to get up and running.

**Comment by jordij** [comment]
Thanks for the feedback. A database is automatically set up but the issue here is different. The user postgres should be able to login into the DB without password. Will look into it.

As a workaround for now, and after your ```vagrant up``` attempt you could run:

```
$ vagrant ssh
$ perl -pi -e "s/^(local\s+all\s+postgres\s+)peer$/\1trust/" /etc/postgresql/9.3/main/pg_hba.conf
$ exit
$ vagrant halt
$ vagrant up --provision
$ vagrant ssh
$ djrun
```

Cheers

**Comment by timheap** [comment]
That worked, and the box is now up and running. Thanks!
