### ISSUE TITLE
Problem with page-editor.js and hallo.js

### ISSUE THREAD

**Issue by SalahAdDin** [springload/wagtailsites#9]
Hi man, how are you?

I try to adapt my site to your site and i try use your custom hallobuttons with my custom hallo plugin, but, i have a error about placeCaretAtEnd, so, i change page-editor.js and hallo.js but still i have this issue, can you halp me?

```hallo.js:47 Uncaught TypeError: jQuery(...)[plugin] is not a function```

I only register my custom plugin, not your other js files.

**Comment by jordij** [comment]
If you just register the Hallo plugins you need in `core/wagtail_hooks.py` then you can probably delete the file in `core/static/wagtailadmin/js/page-editor.js` as it's just an override from the original Wagtail one.

**Comment by jordij** [comment]
I've updated the according to the new Wagtail 1.0 https://github.com/torchbox/wagtail/releases/tag/v1.0 Plenty of stuff has changed in the editor and we've removed some JS. You shouldn't run into any issues, re-open and provide details in case you do.
